# export TAG=v0.0.1
# skaffold build --file-output output/build-$STATE.json
# skaffold render -a output/build-$STATE.json --output output/render.yaml --digest-source local
apiVersion: skaffold/v4beta11
kind: Config
build:
  platforms: ["linux/amd64"]
  # local:
  #   push: false
  cluster:
    concurrency: 0
    pullSecretName: pre-defined-secret
    pullSecretPath: github_token
    randomDockerConfigSecret: false
    randomPullSecret: false
  tagPolicy:
    envTemplate:
      template: "{{.TAG}}"
  artifacts:
  - image: leoligz/hello-world
manifests:
  helm:
    releases:
    - name: hello-world
      chartPath: charts
      setValueTemplates:
        image: "{{.IMAGE_FULLY_QUALIFIED_leoligz_hello_world}}"
      valuesFiles:
      - charts/values.yaml
